language: java

services:
  - docker

install:
  - mvn install -Dgpg.skip -B -V

script:
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)sgit log --pretty=oneline